actions:
  vundle: vim +PluginClean! +PluginInstall +PluginInstall! +qall

config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  # link_on_import: link

dotfiles:
  f_shell_config.sh:
    dst: ~/.config/shell/config.sh
    link: absolute
    src: .config/shell/config.sh
  f_bash_config.sh:
    dst: ~/.config/bash/config.sh
    link: absolute
    src: .config/bash/config.sh
  f_bash_global.sh:
    dst: ~/.config/bash/global.sh
    link: absolute
    src: .config/bash/global.sh
  f_bash_local.sh:
    dst: ~/.config/bash/local.sh
    link: nolink
    src: .config/bash/local.sh
  f_zsh_config.sh:
    dst: ~/.config/zsh/config.sh
    link: absolute
    src: .config/zsh/config.sh
  f_zsh_global.sh:
    dst: ~/.config/zsh/global.sh
    link: absolute
    src: .config/zsh/global.sh
  d_tmux_plugins_tpm:
    dst: ~/.tmux/plugins/tpm
    link: absolute
    src: .tmux/plugins/tpm
  d_vim:
    dst: ~/.vim
    link: absolute
    src: .vim
  f_fzf_preview.sh:
    dst: ~/bin/fzf_preview.sh
    link: absolute
    src: bin/fzf_preview.sh
  f_gitconfig:
    dst: ~/.gitconfig
    link: absolute
    src: .gitconfig
  f_htoprc:
    dst: ~/.config/htop/htoprc
    link: absolute
    src: .config/htop/htoprc
  f_ipython_default:
    dst: ~/.ipython/profile_default/startup/00_default.py
    link: absolute
    src: .ipython/00_default.py
  f_screenrc:
    dst: ~/.screenrc
    link: absolute
    src: .screenrc
  f_abspath.py:
    dst: ~/bin/abspath.py
    link: absolute
    src: bin/abspath.py
  f_tmux_conf:
    dst: ~/.tmux.conf
    link: absolute
    src: .tmux.conf
  f_tmux_sessions_default_conf:
    dst: ~/.tmux/sessions/default.conf
    link: absolute
    src: .tmux/sessions/default.conf
  f_vimrc:
    dst: ~/.vimrc
    link: absolute
    src: .vim/.vimrc
    actions:
    - vundle

profiles:
  christofa-mac.roam.internal:
    dotfiles:
    - f_shell_config.sh
    - f_bash_config.sh
    - f_bash_global.sh
    - f_bash_local.sh
    - f_zsh_config.sh
    - f_zsh_global.sh
    - d_tmux_plugins_tpm
    - d_vim
    - f_fzf_preview.sh
    - f_gitconfig
    - f_htoprc
    - f_ipython_default
    - f_abspath.py
    - f_screenrc
    - f_tmux_conf
    - f_tmux_sessions_default_conf
    - f_vimrc
